### ISSUE TITLE
Put links & info on Form page

### ISSUE THREAD

**Issue by lrouvelas** [eAbsentee/eAbsentee#118]
Raunak, can you make a change today to the eAbsentee Form page?
Adriel made a good argument for why our social media ads should link straight to the Form page: to avoid navigation drop-off. Plus, the ads are running that way now and not easy/quick to get new ads approved.
However, I'm concerned that the starkness of the Form will spook people. Adriel suggested a couple additions to the Form page:
1. Some kind of "About eAbsentee" link at the top so people can get more info if they want it
2. An SSL Lock logo at the bottom and perhaps near the SSN field to give people confidence in its security.
Do you agree with those changes? If so, can you make them today? A big push these last six days!
-L

**Comment by lrouvelas** [comment]
ETA for making change on #1 above? 
Also, at the bottom, which email do you think it better: your name or "applications@eAbsentee.org"?

**Comment by rau** [comment]
#1 tonight. Up to you - I’ll change it to applications if necessary.

**Comment by lrouvelas** [comment]
My instinct says to change to applications. Some folks downstate will likely ask, "What on earth is a raunak?"

**Comment by rau** [comment]
#1 should be up tomorrow by 12 PM. I’ll change it to applications - I
wouldn’t know what a raunak is myself 😂

**Comment by lrouvelas** [comment]
ETA? We are getting near zero applications from our Facebook advertising, despite lots of click-throughs to the Form page itself. They are scaring away.

**Comment by rau** [comment]
Done
