### ISSUE TITLE
API key security

### ISSUE THREAD

**Issue by sumanthratna** [eAbsentee/eAbsentee#180]
Instead of directly storing `API_KEY` and `API_KEY_FCDC` in variables, we could store SHA-512 hashes of them and authenticate by seeing if the SHA-512 hash of the input matches the correct hash. 

https://passlib.readthedocs.io/en/stable/

**Comment by rau** [comment]
I'm making the ability to add groups a feature available to certain superusers on the dashboard. No longer need an API key insomuch as an authenticated account.
