### ISSUE TITLE
Better HTTP return codes for /applications, /reports, and /maps

### ISSUE THREAD

**Issue by sumanthratna** [eAbsentee/eAbsentee#181]
All of the following should return 403:
- `/applications/` and `/appliations/<ID>.pdf`
- `/reports` and `/reports/*.xlsx`
- `/maps`

**Comment by rau** [comment]
@sumanthratna is it possible to access these routes in the first place if they're not within the Flask server's routes? I would assume folders would be inaccessible, but maybe I'm wrong - let me know

**Comment by sumanthratna** [comment]
When I navigate to `/applications/<ID>.pdf` where ID is an actual application ID, get a page from PythonAnywhere that says there was a server-side issue. I think it's because of this:
https://github.com/eAbsentee/eAbsentee/blob/c7b42c5c0867eda362ce2e949fbef81ee67f9d14/app.py#L60-L65
If `session['output_file']` isn't set, then return a 403 (this should be an easy if-statement)

For the other routes (the folder routes), I think I was suggesting that it'd be better to return 403 for `/applications/` instead of a 404 (so we would add a route and hard-code a 403 return) but TBH that's unnecessary. I think the only thing we need to change is the `/applications/<ID>.pdf` problem.

**Comment by rau** [comment]
No longer save applications (instant delete), no longer make reports, no longer plan on creating folders for maps (integrate into dashboard)
