### ISSUE TITLE
Don't commit static/groups.json to VCS

### ISSUE THREAD

**Issue by sumanthratna** [eAbsentee/eAbsentee#185]
**Describe the solution you'd like**
Instead of committing to git after each change to `static/groups.json`, we can just remove `static/groups.json` from version control. 

**Additional context**
If we do this, we can close #179.

**Comment by sumanthratna** [comment]
See eac758f49d566e72e2f1b2eb7907f8149e86574d.

**Comment by rau** [comment]
Done using solution 

https://stackoverflow.com/questions/43762338/how-to-remove-file-from-git-history

to remove from git commit history
