### ISSUE TITLE
Standardize addresses

### ISSUE THREAD

**Issue by rau** [eAbsentee/eAbsentee#186]
**Is your feature request related to a problem? Please describe.**
On the application, users will occasionally submit their address not standardized. For example: 

1060 W Addison St is correct.

1060 w addision st is not.

1060 W ADDISON ST is not.

**Describe the solution you'd like**
Fix the capitalization of street names by auto capitalizing the first letter and making everything else lowercase - however, this may run into some problems when streets have two capital letters, such as McInytre. Is it worth it to address this by running addresses through some sort of service to get the properly formatted name? Or is it better to standardize it and accept the mistakes? How can we address this?

**Describe alternatives you've considered**
We can run addresses through Google's address services, which can return the properly formatted address. But, this costs around .3 cents each time - I don't think this is worth it or feasible to run every single time, plus it'll add a little bit of time to form processing. Instead, I think we should find a way to handle this in-house.

**Comment by sumanthratna** [comment]
https://pypi.org/project/address/ and https://pypi.org/project/usaddress/ both look very easy to use. I'm not sure if the second package supports international addresses, so if we choose to use an external package we should probably use `address`'s `Addresses` class.

**Comment by rau** [comment]
SmartyStreets takes care of this
