### ISSUE TITLE
No copy-of-application 

### ISSUE THREAD

**Issue by lrouvelas** [eAbsentee/eAbsentee#194]
Raunak, strange that you get it below. I just tried again and I'm still not able to get a copy of the application at the end of the process by clicking a link.
Can you ask Sumanth to try it? Please ask him to apply to Testing County for the President election from the following site:
https://scottsurovell.org/vote/

**Comment by sumanthratna** [comment]
Hey Mr. Rouvelas—I just tried and it worked for me. Maybe we can default to emailing to the applicant (initially I forgot to click the check box), but I'm not sure if we'll get rate-limited by the Gmail API.

**Comment by lrouvelas** [comment]
Strange. I'll pick up the thread later today.
