### ISSUE TITLE
Toggling of SSN when inputting

### ISSUE THREAD

**Issue by rau** [eAbsentee/eAbsentee#2]
Some people need to see their SSN when they type it in (especially on mobile), while others want it to be hidden from shoulder-surfers. Use a bit of Javascript to allow users to toggle this.

As soon as done being inputted, allow to be turned off.

https://github.com/TrustTheVote-Project/horatio-server/issues/61

**Comment by rau** [comment]
SSN's are not traditionally hidden as being typed in - perhaps offer the option to toggle it being visible AFTER ssn is done being inputted

**Comment by waldoj** [comment]
It was hidden at the request of people canvassing, who found that people did not want their SSN exposed to canvassers. Perhaps hide it ~500 ms after the fourth digit is entered?

**Comment by rau** [comment]
https://css-tricks.com/better-password-inputs-iphone-style/
