### ISSUE TITLE
Add Instagram

### ISSUE THREAD

**Issue by sumanthratna** [eAbsentee/eAbsentee#239]
link to https://www.instagram.com/voteabsenteeva/

- In the footer, add the Instagram icon to our socials 
https://github.com/eAbsentee/eAbsentee/blob/96380b4b379f8ca993959e4fdaca7a2c69dc12c5/eAbsentee/home/templates/layout.html#L84-L92
- "Share on Instagram" button to the confirmation pages
- add the icon to index, about, and form pages (also see #238)

CC @robert-f-greene:
- should we add Instagram anywhere else?
- do we even want to add Instagram now? if not, feel free to close this issue

**Comment by bayucakra20** [comment]
Hi, I'd would like to work on this issue

**Comment by sumanthratna** [comment]
Hi @bayucakra20! Thanks for your interest in eAbsentee. First, can you create a PR that adds an Instagram icon to the footer? (see the code block reference I posted in the initial issue). You'll want to use the fontawesome icon: https://fontawesome.com/icons/instagram
