### ISSUE TITLE
Favicon/logo background color

### ISSUE THREAD

**Issue by rau** [eAbsentee/eAbsentee#262]
Very minor but irritating issue - I have Dark Reader (dark mode everywhere extension) installed, so I'm not sure if this is just a me problem.

The favicon is perfect, but the black background looks odd in the a) bookmark bar, b) against the menu (black on dark grey, very subtle), and c) tab.

idk what the solution looks like - perhaps just drop the background? mail logo only?

**Comment by sumanthratna** [comment]
navbar logo has been updated in 4f51a88723fdc7562cb94d2b9a749066ff75423d; still need to update favicon

**Comment by sumanthratna** [comment]
favicon fixed in https://github.com/eAbsentee/eAbsentee/commit/d6735bd7f8896a182b938b5601c23774cd959d85 and https://github.com/eAbsentee/eAbsentee/commit/5bc0e983cf81e9f0f768b040aaf7f4a41f5a78af
