### ISSUE TITLE
Remove support for iframes

### ISSUE THREAD

**Issue by sumanthratna** [eAbsentee/eAbsentee#297]
embedding sites (e.g., iframes) comes with a number of security concerns (e.g., clickjacking). We should remove support for iframes (with X-Frame-Options) and instead encourage groups to link to their eAbsentee form

CC @lrouvelas @robert-f-greene

**Comment by lrouvelas** [comment]
Sumanth, I strongly suggest we keep embedding sites for reasons we can
discuss. We will lose a LOT of applicants if they navigate off the
campaigns site.

**Comment by lrouvelas** [comment]
Can you test it to make sure the problem I ran into is gone?
