### ISSUE TITLE
Get newest list of JSON registrar info

### ISSUE THREAD

**Issue by rau** [eAbsentee/eAbsentee#32]

**Comment by sumanthratna** [comment]
We could create an API to fetch information from https://vote.elections.virginia.gov/VoterInformation/PublicContactLookup. We could fetch this info every morning when we create the report but this would probably be excessive. 

This wouldn't be too difficult to implement if we used Django REST Framework but we should probably save for this for the future.

**Comment by rau** [comment]
@waldoj Do you know where we could get the most updated JSON of the registrar information from for now? Did you get it from the above link when you created it?

**Comment by waldoj** [comment]
Oh, no, that link didn’t exist then. I can’t remember where I got it from — probably a single-page HTML list — but I remember hand-encoding it as JSON.
