### ISSUE TITLE
Upload video to site

### ISSUE THREAD

**Issue by rau** [eAbsentee/eAbsentee#46]

**Comment by rau** [comment]
https://www.youtube.com/watch?v=K9NDP05j3CM&feature=youtu.be

**Comment by rau** [comment]
![Layout](https://user-images.githubusercontent.com/33409793/64395138-326fcb00-d027-11e9-84ae-d4d518690364.jpg)

**Comment by sumanthratna** [comment]
Closed by https://github.com/eAbsentee/eAbsentee/commit/31075c86a61d2409092c16c8d5674cf1b2531103.
